language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
before_script: # to get matplotlib to work
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - pytest -v tests
  - cd tests && bash run_test.sh
